### ISSUE TITLE
Make it possible to forbid some inputs / buttons

### ISSUE THREAD

**Issue by hilnius** [Madumbo/Madumbo-Issues#3]
Some actions on my website trigger events like email sending, and I want to be sure that your algorithm does not trigger those inputs

**Comment by sdeprez** [comment]
That's a good idea but potentially tricky depending on how we implement it! A simple solution would be for instance to provide some css selectors to forbid interactions with those elements, would that fit your needs?

We could also automatically detect a special attribute like `data-no-madumbo` but the whole idea of our system is that the developer does not have to modify its code so I'm not very keen on this idea.

**Comment by sdeprez** [comment]
It is now possible! You can provide a button (or any DOM element) ID or text to forbid any interactions with the corresponding element. Note that the ID needs to be an exact match but the text only a substring match.
