### ISSUE TITLE
Make it possible to restrict the visit of some pages

### ISSUE THREAD

**Issue by hilnius** [Madumbo/Madumbo-Issues#4]
I have some administrative pages which I want to be sure your algs do not visit, so it would be cool to be able to restrict some URLs by giving you an URL prefix / contains for example.

**Comment by sdeprez** [comment]
Good idea, we definitively want to implement that soon.

**Comment by sdeprez** [comment]
You can now forbid some urls using a wildcard syntax: `https://www.website.com/admin/*`!
